### ISSUE TITLE
Open TODO's

### ISSUE THREAD

**Issue by TeefanDev** [TeefanDev/FestServe#1]
## Anforderungen

- [ ] linter rules package einheitlich nutzen
- [ ] stricter types wurden genutzt
- [ ] keine hardgecodeten daten
- [ ] kein auskommentierter code
- [ ] keine hardgecodeten farben, schriftgrößen und größen in widgets
- [ ] keine deprecated packages
- [ ] separation of concerns erklären können
- [ ] finale app gebaut als apk im release mode liegt mit namen Fest_Serve auf oberster ebene dieses repositories

### Entwicklung
- [ ] projektstruktur erklären und konsistent benutzen (layer-first architecture)
- [ ] stateful/stateless widget sinnvoll nutzen
- [ ] composition over inheritance beachten
- [ ] separation of concerns für schichten nutzen (model, business, logic, view, services)
- [ ] interfaces als schnittstelle zwischen schichten
- [ ] interfaces als schnittstelle zwischen data layer und business logic
- [ ] für datenpersistenz wird hive, isar, sqlite oder sharedpreferences genutzt

### Doku
- [ ] abstrakte beschreibung in wenigen sätzen
- [ ] ausführliche beschreibung (problem, wer profitiert)
- [ ] kurze beschreibung aller screens und funktionalität
- [ ] beschreibung der architektur inkl. schaubild der layers

### Testing
- [ ] alle funktionen funktionieren
- [ ] verbindung funktioniert
- [ ] kommunikation funktioniert
- [ ] datenbank funktioniert

## Bonus
- [ ] darkmode
- [ ] eigenes icon
- [ ] launch screen
- [ ] responsive (querformat)
- [ ] kleines easter egg
